services:
  - type: web
    name: ton-nom-service
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn soninkara_app.wsgi:application --bind 0.0.0.0:$PORT"
    staticPublishPath: staticfiles
