# Generated by Django 5.2 on 2025-06-16 12:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='publicites/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='publicites/videos/')),
                ('actif', models.BooleanField(default=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoDivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('theatre', 'Théâtre'), ('quiz', 'Quiz'), ('experience_sociale', 'Expérience sociale'), ('humour', 'Humour'), ('autre', 'Autre')], max_length=50)),
                ('fichier_video', models.FileField(upload_to='videos/')),
                ('miniature', models.ImageField(blank=True, null=True, upload_to='miniatures/')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre_vues', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('categorie_personnalisee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.categorievideo')),
            ],
        ),
        migrations.DeleteModel(
            name='Culture',
        ),
        migrations.DeleteModel(
            name='Diaspora',
        ),
        migrations.DeleteModel(
            name='Jeunesse',
        ),
        migrations.DeleteModel(
            name='Religion',
        ),
        migrations.DeleteModel(
            name='Sante',
        ),
        migrations.AddField(
            model_name='actualite',
            name='lecture',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actualite',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actualite',
            name='vue',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chronique',
            name='lecture',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chronique',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chronique',
            name='vue',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='debat',
            name='lecture',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='debat',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='debat',
            name='vue',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evenement',
            name='lecture',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evenement',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evenement',
            name='vue',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='lecture',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='vue',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='live',
            name='lecture',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='live',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='live',
            name='vue',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='musique',
            name='lecture',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='musique',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='musique',
            name='vue',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
