# Generated by Django 5.2 on 2025-06-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_categorievideo_publicite_videodivers_delete_culture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debat',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='debat',
            name='participants',
            field=models.TextField(blank=True),
        ),
    ]
